<?php
/**
 * @file
 * Code for the Collabco Settings Feature feature.
 */

include_once 'collabco_settings_feature.features.inc';

/**
 * Implements hook_init().
 * 
 * We set an integration module context early on, this lets us know we are on an
 * integration page provided by a feature and which content type it is for. 
 * Which can be usefull, Such as for filtering other views and turning on/off 
 * contexts.
 *
 */
function collabco_settings_feature_init() { 
  // Check if the current path starts with node or user.
  if (((arg(0) === 'node') || (arg(0) === 'user')) && is_numeric(arg(1))) {
    // Find all Collabco integrations.
    $integrations = module_invoke_all('collabco_integration');
    foreach($integrations as $integration) {
      if (!empty($integration['tab'])) {
        foreach($integration['tab'] as $label => $data) {
          if (!empty($data['node']) && (arg(2) === $data['subpath'])) {
            context_set('context', 'integration', $data['node']);
          }
        }
      }
    }
  }
}

/**
 * Build the main tab bar for groups and users.
 *
 * @return array - a drupal render array
 */
function collabco_settings_feature_tabs_integration($path, $subpaths = array()) {
  $tab_links = collabco_settings_feature_tabs_integration_links($path, $subpaths);
  $tabs = array(
    'header-content-tab' => array(
      '#theme' => 'item_list',
      '#weight' => 20,
      '#items' => $tab_links,
      '#prefix' => '<div class="header-content-tab">',
      '#suffix' => '</div>',
    ),
  );
  return $tabs;
}

/**
 * Build the links for group or user tabs from whatever features 
 * provide an integration hook with the required details.
 *
 * @return array - a drupal render array
 */
function collabco_settings_feature_tabs_integration_links($path, $subpaths = array()) {
  $links = array();
  $current_path = menu_get_item();
  $integrations = module_invoke_all('collabco_integration');
  foreach($integrations as $integration) {
    if (!empty($integration['tab'])) {
      foreach($integration['tab'] as $label => $data) {
        $subpaths[$label] = '/' . $data['subpath'];
      }
    }
  }
  foreach($subpaths as $label => $subpath) {
    $link_path = $path . $subpath;
    $tab_links[$subpath]['data'] = l($label, $link_path);
    // Set active li for styling.
    if ($link_path == $current_path['href']) {
      $tab_links[$subpath]['class'] = array('active');
    }
  }
  return $tab_links;
}

/**
 * Implements hook_collabco_integration().
 *
 * A simple way of integrating feature module while keeping them modular, ie
 * they can be turned off without affecting each other or the site aversely.
 * 
 * An array of data provides information on views, page paths and  bundle types
 * provided by a module so the can be used elsewhere without hardcoding
 * dependencies.
 */
function hook_collabco_integration() {
  // Add links to views if a module wants to do that.
  return array(
    'off_wiki_feature' => array(
      // Entity will be used in add content links and possibly elsewhere.
      'entity' => array(
        'node'=> array('bundle'),
      ),
      // Provide a link, path and bundle for the group/user tab.
      // The bundle will be available as the value of the 'integration' context,
      // which will be active if we are on the provided subpath.
      'tab' => array(
        'label' => array(
          'subpath' => 'subpath',
          'node' => 'bundle',
        ),
      ),
      // This view will be altered in a standard way for integrations, removing
      // group or node subscription flags if needed and removing node flag if not.
      // an add content button is is a group aware add content link to the
      // provided node bundle.
      'views' => array(
        'view' => array(
          'display_id' => array(
            'subscribe_flag' => array(
              'group_type' => 'node',
              'entity_type' => 'node',
            ),
            'add_content_link' => array(
              'areas' => array('header','footer'),
            ),
          ),
        ),
      ),
    ),
  );
}

